name: development CI

on:
  push:
    branches:
      - 'feat/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Instalar dependencias
        run: npm install
      - name: Executar testes
        run: npm test